apiVersion: v1
kind: Pod
metadata:
  name: toolkit
  #namespace: sas-viya                 ## <-- Specify namespace for the pod to be deployed
spec:
  ## Tolerations
  #nodeSelector:
  #  workload.sas.com/class: stateless  ## <-- Specify nodepool for the pod to be scheduled
  #tolerations:
  #  - key: "workload.sas.com/class"
  #    operator: "Equal"
  #    value: "stateless"               ## <-- Specify nodepool for the pod to be scheduled
  #    effect: "NoSchedule"
  containers:
    - name: toolkit
      image: antonioneri/toolkit:latest
      command: ['sleep', 'infinity']
      #volumeMounts:
      #  - mountPath: "/mount"
      #    name: mount
  ## Storage
  #volumes:
  #  - name: mount
  #    # NFS
  #    nfs:
  #      path: /path/to/dir            ## <-- Specify NFS directory to be mounted
  #      server: nfsserver.domain.com  ## <-- Specify NFS hostname
  #    # PVC
  #    persistentVolumeClaim:
  #      claimName: pvc-name           ## <-- Specify name of PVC to be mounted
  #    # hostPath
  #    hostPath:
  #      path: /path/to/dir            ## <-- Specify hostPath to be mounted
