name: ci

on:
  push:
    branches:
      - "main"

env:
  IMAGE_NAME: antonioneri/toolkit

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get current date
        id: date
        if: ${{ github.ref == 'refs/heads/main' }}
        run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          sbom: true
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.DATE }}
            ${{ env.IMAGE_NAME }}:latest
